### ISSUE TITLE
Ingress spec seems a little broken

### ISSUE THREAD

**Issue by KittyKatt** [pando85/kaniop#59]
Hey there! I'm really excited about what you're doing here as I'm running Kanidm solely in Kubernetes at the moment and I wanted to try to get what you've got so far going. I know this is in REAL early stages and a lot of things aren't implemented yet, but hopefully this might help a little. I'm getting these errors/debug logs in the kaniop pod when deploying a new `Kanidm` object:

```
kaniop-7bc5b54b97-7w9c7 kaniop 2024-11-23T03:17:59.566351Z DEBUG reconciling object:reconcile_kanidm: kube_client::client: Unsuccessful: ErrorResponse { status: "Failure", message: "Ingress.networking.k8s.io \"beep-boop\" is invalid: spec.rules[0].http.paths[0].pathType: Unsupported value: \"\": supported values: \"Exact\", \"ImplementationSpecific\", \"Prefix\"", reason: "Invalid", code: 422 } object.ref=Kanidm.v1beta1.kaniop.rs/beep-boop.kaniop object.reason=object updated
kaniop-7bc5b54b97-7w9c7 kaniop 2024-11-23T03:17:59.569537Z ERROR reconciling object: kaniop_kanidm::controller: msg="failed reconciliation" namespace=kaniop name=beep-boop error=failed to delete Ingress kaniop/beep-boop (kube error: ApiError: ingresses.networking.k8s.io "beep-boop" not found: NotFound (ErrorResponse { status: "Failure", message: "ingresses.networking.k8s.io \"beep-boop\" not found", reason: "NotFound", code: 404 })) object.ref=Kanidm.v1beta1.kaniop.rs/beep-boop.kaniop object.reason=object updated
```

The second seems to be sorta self-explanatory since it's trying to find an Ingress resource the operator couldn't create. I know that the example config probably isn't super fleshed out, but I did my best to adapt it to my needs:
```
apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: beep-boop
spec:
  domain: idm.beep.boop
  image: kanidm/server:1.4.0
  replicaGroups:
    - name: default
      replicas: 3
  logLevel: info
  storage:
    volumeClaimTemplate:
      metadata:
        generateName: kanidm-data
      spec:
        storageClassName: nfs-subdir-provisioned
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
  ingress:
    tlsSecretName: beep-boop-tls
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/service.serversscheme: "https"
```

Any ideas or any ways I can help test? This project is really cool and I'd love to contribute in any way that I can.
